build image:
    image: docker:latest
    script:
        - docker pull $CI_REGISTRY_IMAGE:latest || true
        - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER $CI_REGISTRY --password-stdin
        - docker build --pull --cache-from $CI_REGISTRY_IMAGE:latest -t $CI_REGISTRY_IMAGE:latest .
        - docker push $CI_REGISTRY_IMAGE

include:
  - template: Security/Container-Scanning.gitlab-ci.yml

container_scanning:
  variables:
    CS_IMAGE: $CI_REGISTRY_IMAGE
    CS_SEVERITY_THRESHOLD: low
    CS_IGNORE_UNFIXED: "true"
